# Generated by Django 5.0.6 on 2024-07-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_role_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
    ]
