# Generated by Django 5.0.6 on 2024-07-01 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charges', '0001_initial'),
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.client'),
        ),
        migrations.AddField(
            model_name='cost',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.project'),
        ),
        migrations.AddField(
            model_name='cost',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.task'),
        ),
        migrations.AddField(
            model_name='costapprovalrequest',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.cost'),
        ),
        migrations.AddField(
            model_name='costapprovalrequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.task'),
        ),
    ]
