# Generated by Django 5.0.6 on 2024-07-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='decimal_field',
            new_name='amount',
        ),
    ]
