# Generated by Django 5.0.6 on 2024-07-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0004_cost_created_date_costapprovalrequest_created_date'),
        ('task_management', '0004_client_created_date_industry_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('bill_registered_date', models.DateField()),
                ('bill_paid_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid')], default='back_log', max_length=225)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.client')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.project')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
