# Generated by Django 5.0.6 on 2024-07-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0006_paymentrequest'),
        ('task_management', '0004_client_created_date_industry_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.bill')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.client')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charges.cost')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.project')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.task')),
            ],
        ),
    ]
