# Generated by Django 5.0.6 on 2024-07-01 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.industry')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('active', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('done', 'Done')], default='draft', max_length=225)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('back_log', 'Back Log'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('ready_for_schedule', 'Ready For Schedule'), ('scheduled', 'Scheduled'), ('done', 'Done')], default='back_log', max_length=225)),
                ('deadline_date', models.DateField()),
                ('last_modified_date', models.DateTimeField()),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='user_management.user')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_tasks', to='user_management.user')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task_management.project')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to='user_management.user')),
            ],
        ),
    ]
